config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  # 	resources :users do
  # 		resources :articles do 
  # 			resources :comments
  # 		end	
  # 	end	
  # end

  namespace :admin do
  	resources :users , except: [:destroy] do 
      get "change_password", on: :member
      patch "update_password", on: :member
    end 
    resources :articles , except: [:destroy] do
      get "search_article", on: :collection
    end  
    resources :comments , only: [:index]
    resources :tags , only: [:new,:create]
    resources :sessions, only: [:create] 
    resources :messages, only: [:index,:destroy]
  
  end
  root 'admin/sessions#index'
  get '/login', to: 'admin/sessions#new', as: :admin_login
  delete '/logout', to: 'admin/sessions#destroy', as: :admin_logout
  get 'user/:id/role', to: "admin/users#make_super", as: :make_superadmin
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_tags
	has_many :tags,through: :article_tags
	has_many :comments
	validates :title, :content, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	load_and_authorize_resource
	def index
		#@user = current_user
		#inding.pry
		if current_user.super_admin
			@articles = Article.paginate(page: params[:page], per_page: 5)
		else
			#binding.pry
		  @articles = Article.where(user_id: @current_user.id).paginate(per_page: 5, page: params[:page])
		end  
	end	

	def new
		@tags = Tag.all
	end
	
	def create
		binding.pry
		@article = @current_user.articles.create(article_params_new)
		artilce = params.require(:article)
		@tags = artilce[:tags]
	  @tags.each do |tag_id|
		   ArticleTag.create(article: @article,tag_id: tag_id)
		end 
		redirect_to action: "index"
	end	

	def show
		@article = Article.find(params[:id])
		@tags = @article.tags
	end

	def edit
		#binding.pry
		@user = current_user
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			flash[:notice] = "Article Updated Successfully"
		  @article = index
			render :index
		else
			flash[:notice] = "Article Updation failure"
			render :edit
		end
	end	

	def search_article
		#binding.pry
		search = params[:Search]
		if search == "Title"
			@articles = Article.where('title LIKE ?',"%#{params[:q]}%").paginate(per_page: 5, page: params[:page])
		else
		  @articles = Article.where('content LIKE ?', "%#{params[:q]}%").paginate(per_page: 5, page: params[:page])
		end
		render :index
	end	

	private

	 def article_params
		params.require(:article).permit(:title,:content,:is_publish)
	 end	

   def article_params_new
  	params.require(:article).permit(:title,:content)
   end	
   

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/edit.html.erb
<%= form_for([:admin,@article]) do |form| %>
<p>
	<%= form.label :title %>
	<%= form.text_field :title %>
</p>
<p>
	<%= form.label :content %>
	<%= form.text_area :content,cols: 50, rows: 5 %>
</p>
<p>	
	<% if @current_user.super_admin %>
		<%= form.label :is_publish %>
		<%= form.check_box :is_publish %>
	<% end %>	
</p>
<p>
	<%= form.submit("Update") %>
</p>
<% end %>

app/views/admin/articles/index.html.erb
<h3 align="center">Articles<br>
<%= link_to "Create Article", new_admin_article_path %>
</h3>
<center>
<%= form_tag search_article_admin_articles_path, method: :get do %>
   <%= select_tag "Search", options_for_select([ "Title", "Content" ])%>
   <%= text_field_tag(:q) %>
   <%= submit_tag("Search") %>
<% end %>
</center>
<br>
<table align="center" border="1">
	<tr>
		<td>Title</td>
		<td>Content</td>
		<td>Publish</td>
		<td>Created</td>
		<td colspan="2">Action</td>
	</tr>
	<% @articles.each do |article| %>
	<tr>
		<td><%= article.title%></td>
		<td><%= article.content%></td>
		<td><%= article_publish(article.is_publish, truthy: "Yes", falsey: "No") %></td>
		<td><%= time_data(article.created_at) %></td>
		<td><%= link_to "Edit", edit_admin_article_path(article)%> </td>
		<td><%= link_to "Show", admin_article_path(article)%> </td>

	</tr>
	<% end %>
</table>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">    
<%= will_paginate @article %>
  </ul>
</nav>

app/views/admin/articles/new.html.erb
<h3 align="center">Create New Article</h3>

<%= form_for(:article,url: admin_articles_path) do |f|%>
	<p>
		<%= f.label "tag"%>
		<%= f.select :tags,options_for_select(@tags.collect{ |tag| [tag.name ,tag.id]}),{:include_blank => true},{:multiple => true} %>
	</p>
	<p>
	  <%= f.label :title %>
	  <%= f.text_field :title,:required => true %>
	</p>
	<p>
		<%= f.label :content %>
		<%= f.text_area :content,cols: 30,rows: 5,:required => true %>
	</p>

	<p>
		<%= f.submit("ADD") %>
	</p>
<% end %>
<script>
// Check box style
$("#article_tags").select2({
    theme: "bootstrap"
})
</script>

app/views/admin/articles/show.html.erb
<br>
<div align="center">
	<table border="1">
		<tr>
			<td>Article Tags</td>
			<td><% @tags.each do |tag| %>
				<%= tag_with_hash(tag.name) %>
				<% end %>
			</td>
		</tr>
		<tr>
			<td>Title</td>
			<td><%= @article.title %></td>
		</tr>
		<tr>
			<td>Content</td>
			<td><%= @article.content %></td>
		</tr>
		<tr>
			<td>Publish</td>
			<td><%= article_publish(@article.is_publish, truthy: "Yes", falsey: "No") %></td>
		</tr>
		<tr>
			<td>Created</td>
			<td><%= time_data(@article.created_at) %></td>
		</tr>
		
	</table>
</div>