config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  # 	resources :users do
  # 		resources :articles do 
  # 			resources :comments
  # 		end	
  # 	end	
  # end

  namespace :admin do
  	resources :users , except: [:destroy] do 
      get "change_password", on: :member
      patch "update_password", on: :member
    end 
    resources :articles , except: [:destroy] do
      get "search_article", on: :collection
    end  
    resources :comments , only: [:index]
    resources :tags , only: [:new,:create]
    resources :sessions, only: [:create] 
    resources :messages, only: [:index,:destroy]
  
  end
  root 'admin/sessions#index'
  get '/login', to: 'admin/sessions#new', as: :admin_login
  delete '/logout', to: 'admin/sessions#destroy', as: :admin_logout
  get 'user/:id/role', to: "admin/users#make_super", as: :make_superadmin
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.super_admin?
        can :manage, :all
      else
        can :manage, Article 
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_tags
	has_many :tags,through: :article_tags
	has_many :comments
	validates :title, :content, presence: true
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
	belongs_to :tag
	belongs_to :article
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :article
	has_many :notifications, as: :notifiable
	validates :fullname, :email,:message,presence: true
end

app/models/message.rb
class Message < ApplicationRecord
	has_many :notification, as: :notifiable 
	validates :fullname,:email, :content, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifiable, polymorphic: true
end

app/models/setting.rb
class Setting < ApplicationRecord
	validates :blog_name,:post_per_page,:if_maintance,presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :article_tags
	has_many :articles,through: :article_tags
	validates :name,presence: true
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
	has_secure_password
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
	has_many :articles
	validates :first_name,:about,:email,:password_digest, presence: true
  	validates :email, uniqueness: true,format: { with: VALID_EMAIL_REGEX }
  	validates :first_name, length: {minimum: 3}
  	validates :password_digest , length: {minimum: 6}

  		
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController

	def new 

	end

	def create 
		#binding.pry
		@tag= Tag.create(tag_names) 
		redirect_to root_path
	end	

	private

	def tag_names
		params.require(:tag).permit(:name)
	end	
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	load_and_authorize_resource
	def index
		@user = User.paginate(page: params[:page], per_page: 5)
	end	
	def edit
		@user = User.find(params[:id])
	end	
	def new 

	end 

	def change_password
		@user = User.find(params[:id])
	end	

	def update_password
		#binding.pry
		@user = User.find(params[:id])
		user = params[:user]
		password = user[:password]
		confirm_password = user[:confirm_password]
		if password == confirm_password 
			  @user.password = password
			  if @user.save
		     flash[:notice] = "password Update Successfully"	
				 redirect_to admin_users_path			
			  end 	
		else
			flash[:notice] = "password not match"	
			render :change_password	
		end	
	end
		
	def create
		#binding.pry
		@user = User.create(newuser_params)
		redirect_to admin_users_path			
	end	
	def update
		#byebug
		user = User.find(params[:id])
		if user.update(user_params)
			flash[:notice] = "User Record Update Successfully"
		  @user = User.paginate(page: params[:page], per_page: 5)
			render :index	
		else
			flash[:notice] = "User Updation is failure"	
			render :edit
		end
		#redirect_to admin_users_path	
	end

	def show
		#binding.pry
		@user = User.find(params[:id])
	end	

	
	def make_super
		@u = User.find(params[:id])
		@u.update(super_admin: true)
		@user = User.paginate(page: params[:page], per_page: 5)
	end

	private
	def user_params
		user = params[:user]
		super_admin = user[:super_admin]
		if super_admin == ""
			params.require(:user).permit(:first_name,:last_name,:about,:email)
		else 
			params.require(:user).permit(:first_name,:last_name,:about,:email,:super_admin)
		end
	end	
	
	def newuser_params
		user = params[:user]
		super_admin = user[:super_admin]
		if super_admin == ""
			params.require(:new).permit(:first_name,:last_name,:about,:email,:password)
		else
			params.require(:new).permit(:first_name,:last_name,:about,:email,:password,:super_admin)
		end		
	end	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	before_action :authorize
  before_action :current_user
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to root_path, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
  
  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end 

  def authorize
  	unless current_user 
			flash[:notice] = "Please Login before perform actions"
  		redirect_to admin_login_path
  	end
 	  return 	
 end
 
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	def time_data(time)
		time_ago_in_words(time) + " " + "ago"
	end

  def article_publish(status, truthy: "", falsey: "")
  	if status
  		truthy
  	else
  		falsey
  	end
  end

  def tag_with_hash(name)
    return "#" + name
  end  
  

end

app/views/admin/_home.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Admin Portal</a>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item active">
    <%= link_to "User List",admin_users_path,class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Comment List",admin_articles_path,class: "nav-link" %>
      </li>
      <li class="nav-item active">
    <%= link_to "Aricle List",admin_comments_path,class: "nav-link" %>
      </li>
       </ul>
    <ul class="navbar-nav ml-auto">
      <% unless session[:user_id].nil? %>
          <% @user = User.find(session[:user_id]) %>
          <li class="nav-item active">
           <%=  @user.email %>
          </li> 
      <% end %>
      <li class="nav-item active">
       <%= link_to "Log Out",admin_logout_path,method: :delete,class: "nav-link" %>   
      </li> 
    </ul>   
   

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand">Admin Portal</a>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <% if session[:user_id].nil? %>
      <li class="nav-item active">
      <%= link_to "Log In",admin_login_path,class: "nav-link" %>   
    </li>
    <% else %>
      <li class="nav-item active">
    <%= link_to "Users",admin_users_path,class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "Comments",admin_comments_path,class: "nav-link" %>
      </li>
      <li class="nav-item active">
    <%= link_to "Articles",admin_articles_path,class: "nav-link" %>
      </li>
      <li class="nav-item active">
    <%= link_to "Messages",admin_messages_path,class: "nav-link" %>
      </li>
      <li class="nav-item active">
    <%= link_to "Create Tag",new_admin_tag_path,class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
           <%= @current_user.email %>
      </li> 
      <li class="nav-item active">
       <%= link_to "Log Out",admin_logout_path,method: :delete,class: "nav-link" %>   
      </li> 
    </ul>  
    <% end %>
    <ul class="navbar-nav">
     <li class="nav-item active">
        <% flash.each do |name,msg| %>
        <%= msg %>
        <% end %>
      </li>
    </ul>  
  </div>
</nav>
    <%= yield %>
  </body>
</html>