config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  # 	resources :users do
  # 		resources :articles do 
  # 			resources :comments
  # 		end	
  # 	end	
  # end

  namespace :admin do
  	resources :users , except: [:destroy] do 
      get "change_password", on: :member
      patch "update_password", on: :member
    end 
    resources :articles , except: [:destroy] do
      get "search_article", on: :collection
    end  
    resources :comments , only: [:index]
    resources :tags , only: [:new,:create]
    resources :sessions, only: [:create] 
    resources :messages, only: [:index,:destroy]
  
  end
  root 'admin/sessions#index'
  get '/login', to: 'admin/sessions#new', as: :admin_login
  delete '/logout', to: 'admin/sessions#destroy', as: :admin_logout
  get 'user/:id/role', to: "admin/users#make_super", as: :make_superadmin
end

app/models/message.rb
class Message < ApplicationRecord
	has_many :notification, as: :notifiable 
	validates :fullname,:email, :content, presence: true
end

app/controllers/admin/messages_controller.rb
class Admin::MessagesController < ApplicationController

	 def index
	 	@messages = Message.paginate(page: params[:page], per_page: 5)
	 end
	 
	 def destroy
	 	#binding.pry
	 	message = Message.delete(params[:id])
	 	if message
	 		flash[:notice] = "Message Delete Successfully"	
	 	else
	 		flash[:notice] = "Message Delete Failures"	
	 	end 
	 	redirect_to action: "index"
	 end	

end

app/helpers/admin/messages_helper.rb
module Admin::MessagesHelper
end

app/views/admin/messages/index.html.erb
<h3 align="center">Messages</h3>
<table align="center" border="1">
	<tr>
		<td>Full name</td>
		<td>Email</td>
		<td>Content</td>
		<td>Created</td>
		<td>Action</td>
	
	</tr>
	<% @messages.each do |message| %>
	<tr>
		<td><%= message.fullname%></td>
		<td><%= message.email %></td>
		<td><%= message.content %></td>
		<td><%= time_data(message.created_at) %></td>
		<td>
		<%= link_to "Deleted",admin_message_path(message),method: :delete, 
		data: { confirm: "Are you sure?" }%>
		</td>
	</tr>
	<% end %>	
</table>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">    
   	<%= will_paginate @messages %>
  </ul>
</nav>