config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # namespace :admin do
  # 	resources :users do
  # 		resources :articles do 
  # 			resources :comments
  # 		end	
  # 	end	
  # end

  namespace :admin do
  	resources :users , except: [:destroy] do 
      get "change_password", on: :member
      patch "update_password", on: :member
    end 
    resources :articles , except: [:destroy] do
      get "search_article", on: :collection
    end  
    resources :comments , only: [:index]
    resources :tags , only: [:new,:create]
    resources :sessions, only: [:create] 
    resources :messages, only: [:index,:destroy]
  
  end
  root 'admin/sessions#index'
  get '/login', to: 'admin/sessions#new', as: :admin_login
  delete '/logout', to: 'admin/sessions#destroy', as: :admin_logout
  get 'user/:id/role', to: "admin/users#make_super", as: :make_superadmin
end

app/models/user.rb
require 'bcrypt'
class User < ApplicationRecord
	has_secure_password
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
	has_many :articles
	validates :first_name,:about,:email,:password_digest, presence: true
  	validates :email, uniqueness: true,format: { with: VALID_EMAIL_REGEX }
  	validates :first_name, length: {minimum: 3}
  	validates :password_digest , length: {minimum: 6}

  		
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	load_and_authorize_resource
	def index
		@user = User.paginate(page: params[:page], per_page: 5)
	end	
	def edit
		@user = User.find(params[:id])
	end	
	def new 

	end 

	def change_password
		@user = User.find(params[:id])
	end	

	def update_password
		#binding.pry
		@user = User.find(params[:id])
		user = params[:user]
		password = user[:password]
		confirm_password = user[:confirm_password]
		if password == confirm_password 
			  @user.password = password
			  if @user.save
		     flash[:notice] = "password Update Successfully"	
				 redirect_to admin_users_path			
			  end 	
		else
			flash[:notice] = "password not match"	
			render :change_password	
		end	
	end
		
	def create
		#binding.pry
		@user = User.create(newuser_params)
		redirect_to admin_users_path			
	end	
	def update
		#byebug
		user = User.find(params[:id])
		if user.update(user_params)
			flash[:notice] = "User Record Update Successfully"
		  @user = User.paginate(page: params[:page], per_page: 5)
			render :index	
		else
			flash[:notice] = "User Updation is failure"	
			render :edit
		end
		#redirect_to admin_users_path	
	end

	def show
		#binding.pry
		@user = User.find(params[:id])
	end	

	
	def make_super
		@u = User.find(params[:id])
		@u.update(super_admin: true)
		@user = User.paginate(page: params[:page], per_page: 5)
	end

	private
	def user_params
		user = params[:user]
		super_admin = user[:super_admin]
		if super_admin == ""
			params.require(:user).permit(:first_name,:last_name,:about,:email)
		else 
			params.require(:user).permit(:first_name,:last_name,:about,:email,:super_admin)
		end
	end	
	
	def newuser_params
		user = params[:user]
		super_admin = user[:super_admin]
		if super_admin == ""
			params.require(:new).permit(:first_name,:last_name,:about,:email,:password)
		else
			params.require(:new).permit(:first_name,:last_name,:about,:email,:password,:super_admin)
		end		
	end	
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_userlist.html.erb
<table align="center" border="1">
<thead>
		<tr>
		<th>First Name</th>
		<th>Last Name</th>
		<th>About</th>
		<th>Email</th>
		<th>CreateD</th>
		<th colspan="4">Action</th>
	</tr>	
</thead>		
<tbody>	
<% @user.each do |user| %>
<tr>
	<td><%= user.first_name %> <span class="<%=user.super_admin ? "sp-class" : ""%>"><%=user.super_admin ? "Master" : ""%></span></td>
	<td><%= user.last_name %></td>
	<td><%= user.about %></td>
	<td><%= user.email %>
	<td><%= time_data(user.created_at) %></td>
	<td><%= link_to " Edit ", edit_admin_user_path(user) %></td>	
	<td><%= link_to " Make Super ", make_superadmin_path(user), remote: true %>	</td>
	<td><%= link_to "Show", admin_user_path(user) %>	</td>
	<td><%= link_to "Change Password", change_password_admin_user_path(user) %>	</td>

</tr>
</tbody>
<% end %>
</table>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">    
<%= will_paginate @user %>
  </ul>
</nav>

app/views/admin/users/change_password.html.erb
<h3 align="center">
	<%= @user.first_name%>&nbsp<%= @user.last_name %> Edit Password
</h3>

<%= form_for([:admin,@user],url: update_password_admin_user_path, method: :patch) do |form| %>
	
	<p>
		<%= form.label :password, "New Password" %>
		<%= form.password_field :password,require: true %>
	<p>
		<%= form.label :confirm_password, "Confirm Password" %>
		<%= form.password_field :confirm_password,require: true %>
	</p>
		<%=form.submit("Update Password") %>
	</p>
<% end %>

app/views/admin/users/edit.html.erb
<%= form_for([:admin,@user]) do |form| %>
	<p>
		<%=form.label :first_name %>
		<%=form.text_field :first_name,:required => true %>
	</p>
	<p>
		<%=form.label :last_name %>
		<%=form.text_field :last_name,:required => true %>
	</p>
	<p>
		<%=form.label :about %>
		<%=form.text_area :about,cols: 50, rows: 5,:required => true %>
	</p>
	<p>
		<%=form.label :email %>
		<%=form.email_field :email,:required => true %>
	</p>
		<%= form.label :super_admin %>
		<%= form.check_box :super_admin %>
	<p>
		<%=form.submit("UPDATE") %>
	</p>
<% end %>

app/views/admin/users/index.html.erb
<h3 align="center">Users</h3>
<div id="user_data">
			<%= render "userlist" %>
</div>

<style type="text/css">
	.sp-class {
    color: #398f94;
    border: 1px solid #398f94;
    font-size: 12px;
}
</style>

app/views/admin/users/make_super.js.erb
$("#user_data").html('<%= j render "userlist" %>');

app/views/admin/users/new.html.erb
<h1 align="center">Add User</h1>
<%= form_for(:new,url: admin_users_path) do |f|%>
	<p>
	  <%= f.label :first_name %>
	  <%= f.text_field :first_name,:required => true %>
	</p>
	<p>
	  <%= f.label :lastname %>
	  <%= f.text_field :last_name,:required => true %>
	</p>
  <p>
	  <%= f.label :about %>
	  <%= f.text_field :about,:required => true %>
	</p>
	<p>
	  <%= f.label :email %>
	  <%= f.text_field :email,:required => true %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password ,:required => true%>
	</p>
	<p>
		<%= f.label :super_admin %>
		<%= f.check_box :super_admin %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/admin/users/show.html.erb
<br>
<h3 align="center">
	<%= @user.first_name.capitalize %>&nbsp<%= @user.last_name.capitalize %> Details
</h3>
<div align="center">
	<table border="1">
		<tr>
			<td>First Name</td>
			<td><%= @user.first_name %></td>
		</tr>
		<tr>
			<td>Last Name</td>
			<td><%= @user.last_name %></td>
		</tr>
		<tr>
			<td>About</td>
			<td><%= @user.about %></td>
		</tr>
		<tr>
			<td>Email</td>
			<td><%= @user.email %></td>
		</tr>
		<tr>
			<td>Super Admin</td>
			<td><%= @user.super_admin ? "Yes" : "No" %></td>
		</tr>
	</table>
</div>